### ISSUE TITLE
Thoughts on the Demo

### ISSUE THREAD

**Issue by gonsie** [Submitty/submitty.github.io#1]
I've created a few demo pages for the front end of the homework submission server, check out sample pages here: http://submitty.org/demo/

 The TA page is under construction.

@bmcutler 
@chameco @MasterOdin @JerameyATyler @ZishanHuang @bdrumheller 
@Istyatur

**Comment by MasterOdin** [comment]
* Student View
 * Autograder points is hard to see totals at a glance and feels like it'd be better to just be "4/##" than the long horizontal bar
  * What's the deal with the red exclamation point and green star? 
  * I'm not sure on the icon to go view the PDF of the homework (as I assume that's the arrow).
* TA View
  * I don't like the split in columns between Submission and Grading (and I'm not sure what the submission button would do?)
* Instructor View
  * I think there should be a way to delete gradeables that have been created
  * What's the point of the submission button on "Items Being Graded" and "Graded"?
  * When you publish grades, there should be a way to unpublish as well
  *

**Comment by bmcutler** [comment]
After talking with @ZishanHuang about the purpose of this new student page vs the rainbow grades page...
I thought maybe we should show no grades (#s or bars) on the student navigation page.   You hit a button to see the numbers and the detailed feedback for a gradeable.  Also, there'll be a button at the top of the page to go to the rainbow grades overview.  The student page is just to direct navigation, e.g., green="look here, there's a new [TA grade/rainbow grades update/homework released/etc] you have clicked on yet".   We need to fully discuss what items should be colored/highlighted &when.

@gonsie and I mostly talked about layout.  We didn't go over the icons/symbols in detail.  Those symbols could stay or go or be changed (I think its kinda looking cluttered?).  

Also she didn't finish the updates to the TA view yet.  It will look more similar to the student & instructor view.

**Comment by bmcutler** [comment]
Also...  from the instructor view, the "edit" button on the gradeable goes to the big detailed create new/edit existing gradeable design page we have in the google doc.  The "publish" and "open" buttons are possible shortcuts (needs more though) to specific actions that are also available big edit page.  I think the delete action is rare and could be "hidden" on the big edit page (to avoid accidental deletion).
